name: Client Release on Version Change

on:
  push:
    paths:
      - 'client/pyproject.toml'
    branches:
      - main

jobs:
  release-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get client version number
      id: get_client_version
      run: |
        CLIENT_VERSION=$(grep '^version =' client/pyproject.toml | sed 's/version = "//g' | sed 's/"//g')
        echo "CLIENT_VERSION=$CLIENT_VERSION" > $GITHUB_ENV

    - name: Create Git tag for client
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag "astra-assistants-client-${{ env.CLIENT_VERSION }}"
        git push origin "astra-assistants-client-${{ env.CLIENT_VERSION }}"

    - name: Create GitHub Release for client
      uses: actions/create-release@v1
      with:
        tag_name: "client-${{ env.CLIENT_VERSION }}"
        release_name: "astra-assistants (client) release ${{ env.CLIENT_VERSION }}"
        body: "Automated release for client version ${{ env.CLIENT_VERSION }}"
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

