name: Docker build and publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: docker build and publish
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read Version from File
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build . -t datastax/astra-assistants:${{ env.VERSION }}

      - name: Tag Docker image as latest
        run: |
          docker tag datastax/astra-assistants:${{ env.VERSION }} datastax/astra-assistants:latest

      - name: Push Docker image with version tag
        run: |
          docker push datastax/astra-assistants:${{ env.VERSION }}

      - name: Push Docker image with latest tag
        run: |
          docker push datastax/astra-assistants:latest

